Repository jakehildreth/Locksmith, pull requests merged in 2024-02, with the labels that each got.

#100 Check if the installed version of Locksmith is recent or out of date
  Private/Test-IsRecentVersion.ps1
  README.md
Labels: enhancement, help wanted

#111 Dev 02 Docs and Build 01
  Build/Build-Module.ps1
  README.md
Labels: documentation

#114 Update function docs
  Private/ConvertFrom-IdentityReference.ps1
  Private/Export-RevertScript.ps1
  Private/Find-AuditingIssue.ps1
  Private/Find-ESC1.ps1
  Private/Find-ESC2.ps1
  Private/Find-ESC3Condition1.ps1
  Private/Find-ESC3Condition2.ps1
  Private/Find-ESC4.ps1
  Private/Find-ESC5.ps1
  Private/Find-ESC6.ps1
  Private/Find-ESC8.ps1
  Private/Format-Result.ps1
  Private/Get-ADCSObject.ps1
  Private/Get-CAHostObject.ps1
  Private/Get-RestrictedAdminModeSetting.ps1
  Private/Get-Target.ps1
  Private/Invoke-Scans.ps1
  Private/New-OutputPath.ps1
  Private/Set-AdditionalCAProperty.ps1
  Private/Test-IsProtectedUser.ps1
  Private/Test-IsRecentVersion.ps1
Labels: documentation, enhancement

#119 Take 3 🎬 Fix Protected Users check
  Private/Test-IsMemberOfProtectedUsers.ps1
  Private/Test-IsProtectedUser.ps1
Labels: bug
