Repository jakehildreth/Locksmith, pull requests merged in 2024-01, with the labels that each got.

#99 Add PSScriptAnalyzer action
  .github/workflows/powershell.yml
Labels: enhancement

#101 MegaLinter
  .github/workflows/mega-linter.yml
Labels: enhancement

#102 because a repo isn't complete until it has badges!
  README.md
Labels: documentation

#98 Add ownership remediation to mode 4
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Invoke-Locksmith.ps1
  Locksmith.psd1
  Private/Export-RevertScript.ps1
  Private/Find-ESC8.ps1
  Private/Format-Result.ps1
  Private/Invoke-Remediation.ps1
  Private/New-Dictionary.ps1
  Public/Invoke-Locksmith.ps1
Labels: documentation, enhancement

#104 Fixes "Unable to index into an object..." Errors
  Invoke-Locksmith.ps1
  Private/Find-AuditingIssue.ps1
  Private/Find-ESC6.ps1
  Private/Find-ESC8.ps1
Labels: bug
